name: JJArt
favicon: null
layout_spectrum: 0.6006138832308352
typography_spectrum: 0.8805155465379357
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9b8965'
    - '#dcd8a8'
    - '#554f2f'
    - '#9b241e'
    - '#ac4c4d'
  brandStrength: 0.6978719956241548
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
